# Generated by Django 4.2.10 on 2024-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.CharField(max_length=200),
        ),
    ]
